remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: iswearimnotjay's homepage
description: ![rah](https://github.com/iswearimnotjay/iswearimnotjay.github.io/assets/113044914/98b3e3f2-1355-438b-8c05-62a21e1846e5)

