remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: iswearimnotjay's homepage
description: <img src="https://github.com/iswearimnotjay/iswearimnotjay.github.io/assets/113044914/6d0accf3-87d0-42ea-87df-3425d7a47a2b)https://github.com/iswearimnotjay/iswearimnotjay.github.io/assets/113044914/6d0accf3-87d0-42ea-87df-3425d7a47a2b" width="200">

